apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-my
  namespace: argocd
spec:
  project: default
  source:
    # The URL of new public GitHub repository
    repoURL: https://github.com/AlwaysSayNo/quorum-based-manifests-governance-test.git
    targetRevision: HEAD
    path: app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      name: application-my  # Matches its own name and namespace
      namespace: argocd
      jsonPointers:
      - /spec/source/targetRevision
    - group: governance.nazar.grynko.com
      kind: ManifestRequestTemplate
      jsonPointers:
      - /status
      - /metadata/finalizers
