apiVersion: governance.nazar.grynko.com/v1alpha1
kind: ManifestRequestTemplate

metadata:
  name: mrt-sample
  namespace: test-app

spec:
	# Version is the current version of the ManifestRequestTemplate.
	# Each new MRT must have a version higher than the previous one.
  version: 1
	# publicKey is used to sign MCA.
  publicKey: |
    -----

  # ArgoCDApplicationName is the name of the ArgoCD Application.
  # It should contain information about the git repository, branch and path where manifests are stored.
  argoCDApplication:
    name: test-app
    namespace: argocd

	# Location contains information about where to store MSR, MCA and signatures.
  location:
    folder: manifest-signing-requests

  # MSR contains information about MSR metadata.
  msr:
    name: msr-sample
    namespace: test-app
  
  # MCA contains information about MCA metadata.
  mca:
    name: mca-sample
    namespace: test-app

  # Governance configuration.
  governors:
    notificationChannels:
      - slack:
          channelID: C87654321
    members:
      - alias: owner 
        publicKey: |
          -----
      - alias: voter1
        publicKey: |
          -----
      - alias: voter2
        publicKey: |
          -----

  # The policy rules for approvals.
  require:
    all: true
    require:
      - signer: $owner 
      - atLeast: 2
        require:
          - signer: $voter1
          - signer: $voter2