apiVersion: governance.nazar.grynko.com/v1alpha1
kind: ManifestRequestTemplate

metadata:
  name: mrt-sample
  namespace: test-app

spec:
  version: 1
  publicKey: |
    -----

  argoCDApplication:
    name: test-app
    namespace: argocd

  location:
    folder: manifest-signing-requests

  msr:
    name: msr-sample
    namespace: test-app
  
  mca:
    name: mca-sample
    namespace: test-app

  governors:
    notificationChannels:
      - slack:
          channelID: C87654321
    members:
      - alias: owner 
        publicKey: |
          -----
      - alias: voter1
        publicKey: |
          -----
      - alias: voter2
        publicKey: |
          -----

  require:
    all: true
    require:
      - signer: $owner 
      - atLeast: 2
        require:
          - signer: $voter1
          - signer: $voter2