apiVersion: manifestrequesttemplates.governance/v1alpha1
kind: ManifestRequestTemplate

metadata:
  name: mrt-sample
  namespace: ns1
  version: 1

spec:
  publicKey: |
    -----

  argoCDApplication:
    name: test-app
    namespace: argocd

  location:
    folder: manifest-signing-requests

  msr:
    name: msr-sample
    namespace: ns1
  
  mca:
    name: mca-sample
    namespace: ns1

  governors:
    notificationChannels:
      - slack:
          groupID: C87654321
    members:
      - alias: voter1
        publicKey: |
          -----
        notificationChannel:
          slack:
            userGroupID: C12345678
      - alias: voter2
        publicKey: |
          -----

  require:
    all: true
    require:
      - signer: 
      - atLeast: 2
        require:
          - signer: 
          - signer: 
