apiVersion: governance.nazar.grynko.com/v1alpha1
kind: ManifestSigningRequest

metadata:
  name: msr-sample
  namespace: test-app

spec:
	# Each new MSR must have a version higher than the previous one.
  version: 15
	# publicKey is used to sign MCA.
  publicKey: |
    -----

  # repository contains information about the git repository, branch and path where manifests are stored.
  repository:
    url: https://github.com/AlwaysSayNo/quorum-based-manifests-governance-test.git
    targetRevision: HEAD
    path: app-manifests

	# Location contains information about where to store MSR, MCA and signatures.
  location:
    folder: manifest-signing-requests

  changes:
    - kind: Deployment
      status: Modified
      name: my-deployment
      namespace: test-app
      sha256: abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890
    - kind: Service
      status: New
      name: my-service
      namespace: test-app
      sha256: 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
    # ...

  # Governance configuration.
  governors:
    notificationChannels:
      - slack:
          channelID: C87654321
    members:
      - alias: owner 
        publicKey: |
          -----
      - alias: voter1
        publicKey: |
          -----
      - alias: voter2
        publicKey: |
          -----
      # ...

  # The policy rules for approvals.
  require:
    all: true
    require:
      - signer: $owner 
      - atLeast: 2
        require:
          - signer: $voter1
          - signer: $voter2
      # ...