# Summary of NEW and MODIFIED resources
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-my
  namespace: argocd
spec:
  project: default
  source:
    # The URL of new public GitHub repository
    repoURL: https://github.com/AlwaysSayNo/quorum-based-manifests-governance-test.git
    targetRevision: HEAD
    path: app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      name: application-my # Matches its own name and namespace
      namespace: argocd
      jsonPointers:
        - /spec/source/targetRevision
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-delete-1-my
  namespace: test-ns
data:
  version2: v17677177552223
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-delete-my
  namespace: test-ns
data:
  version1: v1767717755q22
